### ISSUE TITLE
ListSnapshots causes a panic

### ISSUE THREAD

**Issue by aleofreddi** [aleofreddi/csi-sanlock-lvm#7]
```
I0318 10:59:00.866137    6099 grpclogger.go:29] gRPC[6]: call /csi.v1.Controller/ListSnapshots
panic: runtime error: index out of range [1] with length 1

goroutine 36 [running]:
github.com/aleofreddi/csi-sanlock-lvm/driverd/pkg.volumeIdToVgLv(...)
	/root/csi-sanlock-lvm/driverd/pkg/controllerserver.go:574
github.com/aleofreddi/csi-sanlock-lvm/driverd/pkg.(*controllerServer).ListSnapshots(0xc00010ec90, 0xa688c0, 0xc0001e4c90, 0xc0001f6c60, 0x0, 0x0, 0x0)
	/root/csi-sanlock-lvm/driverd/pkg/controllerserver.go:532 +0x8e4
github.com/container-storage-interface/spec/lib/go/csi._Controller_ListSnapshots_Handler.func1(0xa688c0, 0xc0001e4c90, 0x9759c0, 0xc0001f6c60, 0xc0001d8aa0, 0x2, 0x2, 0xc0001e8a80)
	/root/go/pkg/mod/github.com/container-storage-interface/spec@v1.2.0/lib/go/csi/csi.pb.go:5326 +0x86
github.com/aleofreddi/csi-sanlock-lvm/lvmctrld/pkg.GrpcLogger(0xa688c0, 0xc0001e4c90, 0x9759c0, 0xc0001f6c60, 0xc0001e8a60, 0xc0001e8a80, 0xc0001d8b30, 0x55dab8, 0x95aee0, 0xc0001e4c90)
	/root/csi-sanlock-lvm/lvmctrld/pkg/grpclogger.go:31 +0x210
github.com/container-storage-interface/spec/lib/go/csi._Controller_ListSnapshots_Handler(0x96caa0, 0xc00010ec90, 0xa688c0, 0xc0001e4c90, 0xc0001f6c00, 0x9d32c8, 0xa688c0, 0xc0001e4c90, 0xc0001e2300, 0xf)
	/root/go/pkg/mod/github.com/container-storage-interface/spec@v1.2.0/lib/go/csi/csi.pb.go:5328 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000080c00, 0xa6cf00, 0xc000228300, 0xc0001fc300, 0xc0001424e0, 0xde9730, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/grpc/grpc-go@v1.27.0/server.go:1024 +0x4f4
google.golang.org/grpc.(*Server).handleStream(0xc000080c00, 0xa6cf00, 0xc000228300, 0xc0001fc300, 0x0)
	/root/go/pkg/mod/github.com/grpc/grpc-go@v1.27.0/server.go:1313 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001480b0, 0xc000080c00, 0xa6cf00, 0xc000228300, 0xc0001fc300)
	/root/go/pkg/mod/github.com/grpc/grpc-go@v1.27.0/server.go:722 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
```

**Comment by aleofreddi** [comment]
Fixed in 297e99bca28760491232b2a1047fc6d328fef44f
